# Imagen base con Python
FROM python:3.12-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar dependencias primero (mejora el cache de Docker)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000

# Copiar el resto del código
COPY ./app ./app

# Comando que se ejecuta al iniciar el contenedor
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]